### ISSUE TITLE
Highlighting selected tree node

### ISSUE THREAD

**Issue by stefanfrede** [vpusher/paper-tree#16]
Everythings seems to work, except for highlighting the selected tree node and I can't figure out why.

This is my code: https://gist.github.com/0ef305ce3167469c01bc34260a430cec.

What am I doing wrong? Thank you!

**Comment by vpusher** [comment]
@stefanfrede Can you provide some plunkr or any live example ?

**Comment by stefanfrede** [comment]
I will try to set something up.

**Comment by stefanfrede** [comment]
I set up a Plunker (https://embed.plnkr.co/tPHRQURn9nmHDFbIKQ2o/) and realized paper-tree is working as expected. So my problem comes from somewhere else (something is overwriting the selected state), and I close this issue.
