### ISSUE TITLE
Examples of changing the +/- icons

### ISSUE THREAD

**Issue by hegsie** [vpusher/paper-tree#7]
Hi,

Do you have any examples of changing the +/- icons to an different icon?

Regards

**Comment by vpusher** [comment]
@hegsie, currently you can only use the `--paper-tree-toggle-theme` mixin to override the style of the expand/collapse icons. To change the icon simply use the `content` CSS property and set the unicode character you need as value. You can see a sample of this mixin in the lazyloading demo.

I know something better can be done here, probably using an **iron-icon** instead. I need to think a bit about it and noticeably on the API/Mixin opening.

**Comment by vpusher** [comment]
@hegsie if the related mixin is not enough for you, please feel free to open an issue as a feature request or better, submit a PR.
